name: CI
on: [push]

permissions: read-all

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build package
      run: |
        mkdir dist
        tar -czvf dist/mytool.tar.gz ./main.sh

    - name: Upload package to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: dist
  
  scan:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download package from artifacts
      uses: actions/download-artifact@v2
      with:
        name: pkg
        path: dist

    - name: Run some scan tool
      uses: ./.github/actions/harmless-scanner
      with:
        path: dist

  release:
    runs-on: ubuntu-latest

    needs: scan

    steps:
    - name: Download package from artifacts
      uses: actions/download-artifact@v2
      with:
        name: pkg
        path: dist
    
    - name: Publish to package repository
      run: |
        echo "Publishing dist/mytool.tar.gz"
        tar xvzf dist/mytool.tar.gz
